Bamberger
JohanVillanueva/cloudunt-bootcamp pull request #21
Opened 2020-10-10 02:08 UTC by BJBP

2020-10-14 15:19 UTC, JohanVillanueva commented on Session 02/projects/Bamberger Braggi/index.html
> +      <section0>
Evitemos usar etiquetas html inexistentes y que rompen con nuestra semántica.

La etiqueta original es < section >, si queremos decir que es nuestra primera sección usemo clases o id. Por ejemplo:

`
<section class="seccion-1">
`

2020-10-14 15:34 UTC, JohanVillanueva requested changes
Buen trabajo @BJBP!

Por favor revisar los comentarios adjuntos para realizar las correcciones necesarias y subirlas.

2020-10-14 15:34 UTC, JohanVillanueva commented on Session 02/projects/Bamberger Braggi/index.html
> +        <p></p>
Tratemos de evitar dejar etiquetas sin contenido, en este caso el texto debajo debería estar dentro de la etiqueta párrafo para mantener el orden.

2020-10-14 15:34 UTC, JohanVillanueva commented on Session 02/projects/Bamberger Braggi/index.html
> +    <link rel='stylesheet' href='styles.css' />
Las etiquetas links deberían estar dentro de la sección de metadatos de nuestro documento; es decir, dentro de < head >.

2020-10-14 15:34 UTC, JohanVillanueva commented on Session 02/projects/Bamberger Braggi/styles.css
> +  float: left;
En conjunto con una buena maquetación, el uso de la propiedad float debería ser solo para casos excepcionales. En este caso, para este componente no deberíamos usarlo.

2020-10-14 15:34 UTC, JohanVillanueva commented on Session 02/projects/Bamberger Braggi/styles.css
> +  background-color: #39cfcd;
Usemos variables CSS para valores importantes de nuestro documento como colores y tamaños.

2020-10-14 15:34 UTC, JohanVillanueva commented on Session 02/projects/Bamberger Braggi/styles.css
> +  height: 7cm;
Para medidas estáticas es preferible usar 'px' ya que es la medida estática más usada por todas las pantallas de diversos dispositivos para referirse a su tamaño.

2020-10-14 15:34 UTC, JohanVillanueva commented on Session 02/projects/Bamberger Braggi/styles.css
> +  border-radius: 0px 0px 10px 0px;
Si queremos dar bordes redondeados a una sola esquina de nuestro elemento, usemos las propiedades específicas para ello:
 En este caso sería: 
`border-bottom-right-radius: 10px`

2020-10-14 15:34 UTC, JohanVillanueva commented on Session 02/projects/Bamberger Braggi/styles.css
> +  margin-right: 10%;
Para dar márgenes tenemos la versión simplificada de esta propiedad. En este caso sería:

`margin: 10%;`

Esto aplica el margen a todos los lados. Revisar: https://cssreference.io/property/margin/

2020-10-14 15:34 UTC, JohanVillanueva commented on Session 02/projects/Bamberger Braggi/styles.css
> +/*
Evitemos código comentado en nuestros documentos

2020-10-18 03:46 UTC, BJBP commented on Session 02/projects/Bamberger Braggi/index.html
> +      <section0>
De esta forma?:
```
  </head>
  <body>
    <article>
      <section class="seccion-1">
...
      </section>
```

2020-10-18 03:48 UTC, BJBP commented on Session 02/projects/Bamberger Braggi/index.html
> +        <p></p>
Lo deje en caso de que lo vuelva a utilizar, también pensaba hacerlo comentario, pero no tuve tiempo en ese momento.

2020-10-27 00:16 UTC, merged